// CuraAssist CareHub - Data Store & Internationalization Dictionaries

const INITIAL_DATA = {
  // Auth State Mock
  userAuth: {
    isLoggedIn: true,
    user: {
      name: "Alex Morgan",
      email: "alex.morgan@curaassist.health",
      phone: "+1 (555) 019-2834",
      token: "jwt-token-xyz-88219"
    }
  },

  // Active User & Family Members
  familyMembers: [
    {
      id: "mem-1",
      name: "Alex Morgan",
      relation: "Self (Primary)",
      age: 34,
      gender: "Male",
      bloodGroup: "O+",
      height: "178 cm",
      weight: "74 kg",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
      allergies: ["Penicillin", "Dust Mites"],
      conditions: ["Mild Hypertension", "Seasonal Allergies"],
      surgeries: ["Appendectomy (2018)"],
      vitals: {
        heartRate: 72,
        bp: "120/80",
        spO2: 98,
        glucose: 95,
        sleepHours: 7.5,
        steps: 8420,
        stepGoal: 10000
      }
    },
    {
      id: "mem-2",
      name: "Eleanor Morgan",
      relation: "Mother",
      age: 62,
      gender: "Female",
      bloodGroup: "A+",
      height: "162 cm",
      weight: "68 kg",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250",
      allergies: ["Sulfa Drugs"],
      conditions: ["Type 2 Diabetes", "Osteoarthritis"],
      surgeries: ["Knee Arthroscopy (2021)"],
      vitals: {
        heartRate: 76,
        bp: "132/84",
        spO2: 97,
        glucose: 142,
        sleepHours: 6.8,
        steps: 4150,
        stepGoal: 6000
      }
    },
    {
      id: "mem-3",
      name: "Sarah Morgan",
      relation: "Spouse",
      age: 32,
      gender: "Female",
      bloodGroup: "B+",
      height: "168 cm",
      weight: "60 kg",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=250",
      allergies: ["Lactose"],
      conditions: ["Asthma"],
      surgeries: ["None"],
      vitals: {
        heartRate: 68,
        bp: "115/75",
        spO2: 99,
        glucose: 88,
        sleepHours: 8.0,
        steps: 9120,
        stepGoal: 10000
      }
    },
    {
      id: "mem-4",
      name: "Leo Morgan",
      relation: "Son",
      age: 7,
      gender: "Male",
      bloodGroup: "O+",
      height: "122 cm",
      weight: "24 kg",
      avatar: "https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?auto=format&fit=crop&q=80&w=250",
      allergies: ["Peanuts"],
      conditions: ["Childhood Eczema"],
      surgeries: ["Tonsillectomy (2023)"],
      vitals: {
        heartRate: 85,
        bp: "105/70",
        spO2: 99,
        glucose: 90,
        sleepHours: 9.5,
        steps: 11200,
        stepGoal: 10000
      }
    }
  ],

  // Medicine Schedule per member
  medicineSchedule: {
    "mem-1": [
      { id: "sch-1", name: "Lipitor (Atorvastatin)", dose: "20mg - 1 Pill", time: "Morning (08:00 AM)", slot: "morning", taken: true, icon: "pill", refillsLeft: 12, total: 30 },
      { id: "sch-2", name: "Vitamin D3 Supplement", dose: "1000 IU", time: "Afternoon (01:00 PM)", slot: "afternoon", taken: true, icon: "sun", refillsLeft: 25, total: 60 },
      { id: "sch-3", name: "Metoprolol Succinate", dose: "25mg - 1 Tablet", time: "Evening (08:00 PM)", slot: "evening", taken: false, icon: "heart", refillsLeft: 4, total: 30 },
      { id: "sch-4", name: "Melatonin Sleep Aid", dose: "5mg", time: "Night (10:30 PM)", slot: "night", taken: false, icon: "moon", refillsLeft: 18, total: 30 }
    ],
    "mem-2": [
      { id: "sch-10", name: "Metformin XR", dose: "500mg - 2 Tablets", time: "Morning (08:30 AM)", slot: "morning", taken: true, icon: "activity", refillsLeft: 15, total: 60 },
      { id: "sch-11", name: "Glimepiride", dose: "2mg - 1 Tablet", time: "Afternoon (01:30 PM)", slot: "afternoon", taken: false, icon: "pill", refillsLeft: 5, total: 30 }
    ]
  },

  // Health Records
  healthRecords: [
    {
      id: "rec-1",
      memberId: "mem-1",
      title: "Annual Cardiovascular Evaluation",
      category: "Prescriptions",
      date: "2026-07-15",
      doctor: "Dr. Robert Chen, MD",
      facility: "Metro Heart Care Institute",
      tags: ["Cardiology", "Hypertension"],
      fileType: "PDF",
      fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      summary: "Patient shows stable BP response to Metoprolol. Cholesterol levels within normal range."
    },
    {
      id: "rec-2",
      memberId: "mem-1",
      title: "Comprehensive Metabolic & Lipid Panel",
      category: "Lab Reports",
      date: "2026-06-28",
      doctor: "Dr. Sarah Jenkins",
      facility: "Quest Diagnostics Lab",
      tags: ["Blood Test", "Cholesterol", "HbA1c"],
      fileType: "PDF",
      summary: "Fasting Blood Sugar: 95 mg/dL. Total Cholesterol: 175 mg/dL. HbA1c: 5.4% (Normal)."
    },
    {
      id: "rec-3",
      memberId: "mem-1",
      title: "COVID-19 Booster & Flu Vaccine Cert",
      category: "Vaccination",
      date: "2025-11-10",
      doctor: "City Health Clinic",
      facility: "Central Immunization Hub",
      tags: ["Vaccine", "Immunization"],
      fileType: "PDF",
      summary: "Updated Quadrivalent Influenza and Pfizer updated Spikevax vaccine administered."
    },
    {
      id: "rec-4",
      memberId: "mem-2",
      title: "Diabetic Retinopathy Eye Screening",
      category: "Scans",
      date: "2026-05-12",
      doctor: "Dr. Aris Thorne",
      facility: "Vision Health Center",
      tags: ["Ophthalmology", "Diabetes"],
      fileType: "PDF",
      summary: "Fundus examination shows no vascular lesions or retinopathy signs."
    }
  ],

  // Detailed Medicines List with Barcode, Usage, Side Effects & Warnings
  medicines: [
    {
      id: "med-para",
      name: "Paracetamol 650 mg",
      genericName: "Paracetamol / Acetaminophen",
      brandName: "Paracetamol 650",
      barcode: "8907771112233",
      category: "Pain Relief",
      subcategory: "Fever Reducer",
      price: 28.00,
      genericPrice: 8.00,
      savingsPercent: 71,
      rating: 4.9,
      reviewsCount: 890,
      rxRequired: false,
      form: "Tablet",
      packSize: "15 Tablets",
      dosage: "1 Tablet every 6 hours as needed for fever/pain",
      salt: "Paracetamol 650mg",
      manufacturer: "Micro Labs",
      genericManufacturer: "Cipla Generics",
      description: "Effective relief from fever, mild to moderate headache, body pain, and inflammation.",
      sideEffects: ["Mild nausea"],
      usageInstructions: "Take with or without food. Do not exceed 4000mg in 24 hours.",
      safetyWarnings: "Overdose can cause serious liver injury.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-vitc",
      name: "Vitamin C 500 mg",
      genericName: "Ascorbic Acid",
      brandName: "Celin 500",
      barcode: "8908882223344",
      category: "Vitamins & Supplements",
      subcategory: "Immunity Booster",
      price: 45.00,
      genericPrice: 15.00,
      savingsPercent: 66,
      rating: 4.8,
      reviewsCount: 450,
      rxRequired: false,
      form: "Tablet",
      packSize: "30 Tablets",
      dosage: "1 Tablet daily after breakfast",
      salt: "Ascorbic Acid 500mg",
      manufacturer: "GSK Health",
      genericManufacturer: "Sun Pharma",
      description: "Essential antioxidant vitamin for boosting collagen synthesis and immune defense.",
      sideEffects: ["Mild stomach acidity if taken on empty stomach"],
      usageInstructions: "Chew or swallow tablet with water after meal.",
      safetyWarnings: "Consult doctor if history of kidney stones.",
      image: "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-dolo",
      name: "Dolo 650 mg",
      genericName: "Paracetamol Extended Relief",
      brandName: "Dolo (Micro Labs)",
      barcode: "8909993334455",
      category: "Pain Relief",
      subcategory: "Fever Reducer",
      price: 30.00,
      genericPrice: 10.00,
      savingsPercent: 67,
      rating: 4.9,
      reviewsCount: 1250,
      rxRequired: false,
      form: "Tablet",
      packSize: "15 Tablets",
      dosage: "1 Tablet every 6 hours",
      salt: "Paracetamol 650mg",
      manufacturer: "Micro Labs Ltd",
      genericManufacturer: "Generic Care",
      description: "Fast relief from fever, flu symptoms, joint pain, and muscle ache.",
      sideEffects: ["Rare allergic skin rash"],
      usageInstructions: "Swallow whole with water.",
      safetyWarnings: "Avoid alcohol intake while taking paracetamol.",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-1",
      name: "Lipitor",
      genericName: "Atorvastatin Calcium",
      brandName: "Lipitor (Pfizer)",
      barcode: "8901234567890",
      category: "Prescription",
      subcategory: "Heart & Cholesterol",
      price: 48.50,
      genericPrice: 9.20,
      savingsPercent: 81,
      rating: 4.8,
      reviewsCount: 342,
      rxRequired: true,
      form: "Tablet",
      packSize: "30 Tablets (20mg)",
      dosage: "20mg once daily in the evening",
      salt: "Atorvastatin 20mg",
      manufacturer: "Pfizer Pharmaceuticals",
      genericManufacturer: "Teva / Cipla Generics",
      description: "Lowers LDL cholesterol and triglycerides in blood while raising HDL. Reduces risk of heart attack and stroke.",
      sideEffects: ["Mild muscle pain", "Headache", "Nausea", "Elevated liver enzymes"],
      usageInstructions: "Swallow tablet whole with a glass of water. Avoid grapefruit juice while taking this medication.",
      safetyWarnings: "Do not use during pregnancy. Inform doctor if severe muscle weakness occurs.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-2",
      name: "Glucophage",
      genericName: "Metformin Hydrochloride XR",
      brandName: "Glucophage (Merck)",
      barcode: "8909876543210",
      category: "Diabetes Care",
      subcategory: "Blood Glucose Control",
      price: 36.00,
      genericPrice: 7.50,
      savingsPercent: 79,
      rating: 4.7,
      reviewsCount: 215,
      rxRequired: true,
      form: "Extended Release Tablet",
      packSize: "60 Tablets (500mg)",
      dosage: "500mg twice daily with meals",
      salt: "Metformin HCl 500mg",
      manufacturer: "Merck Healthcare",
      genericManufacturer: "Sun Pharma Generics",
      description: "First-line medication for treatment of type 2 diabetes, improves insulin sensitivity and lowers liver glucose production.",
      sideEffects: ["Upset stomach", "Diarrhea", "Metallic taste", "Vitamin B12 depletion"],
      usageInstructions: "Take with meals to reduce gastrointestinal side effects.",
      safetyWarnings: "Not recommended for patients with severe kidney impairment.",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-3",
      name: "Ventolin HFA",
      genericName: "Albuterol Sulfate Inhaler",
      brandName: "Ventolin (GSK)",
      barcode: "8905554443322",
      category: "Respiratory",
      subcategory: "Asthma & COPD",
      price: 64.00,
      genericPrice: 18.00,
      savingsPercent: 72,
      rating: 4.9,
      reviewsCount: 480,
      rxRequired: true,
      form: "Inhaler",
      packSize: "200 Actuations (90mcg)",
      dosage: "1-2 puffs every 4-6 hours as needed for bronchospasm",
      salt: "Albuterol 90mcg",
      manufacturer: "GlaxoSmithKline",
      genericManufacturer: "Prasco / Perrigo",
      description: "Fast-acting bronchodilator for relieving shortness of breath and wheezing in asthma attacks.",
      sideEffects: ["Shakiness", "Increased heart rate", "Nervousness", "Throat irritation"],
      usageInstructions: "Shake well before use. Inhale deeply while depressing canister.",
      safetyWarnings: "Seek immediate medical care if shortness of breath persists after 2 puffs.",
      image: "https://images.unsplash.com/photo-1550572017-edd951b55104?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-4",
      name: "Centrum Adult Multivitamin",
      genericName: "Daily Multi-Mineral & Vitamin Complex",
      brandName: "Centrum Complete",
      barcode: "8901112223334",
      category: "Vitamins & Supplements",
      subcategory: "Wellness",
      price: 19.99,
      genericPrice: 11.50,
      savingsPercent: 42,
      rating: 4.6,
      reviewsCount: 620,
      rxRequired: false,
      form: "Gummy / Tablet",
      packSize: "100 Gummies",
      dosage: "1 Gummy daily with food",
      salt: "Vitamins A, C, D3, E, B6, B12, Zinc, Iron",
      manufacturer: "Haleon",
      genericManufacturer: "Nature Made / CarePlus",
      description: "Complete daily nutrition support for immunity, energy metabolism, and cellular vitality.",
      sideEffects: ["Mild constipation if taken on empty stomach"],
      usageInstructions: "Chew thoroughly before swallowing.",
      safetyWarnings: "Keep out of reach of children. Accidental overdose of iron-containing products is a leading cause of fatal poisoning in children.",
      image: "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&q=80&w=300"
    }
  ],

  // First Aid Guide Dataset
  firstAidGuides: [
    {
      id: "fa-1",
      title: "Cardiopulmonary Resuscitation (CPR)",
      category: "Critical",
      icon: "heart-pulse",
      steps: [
        "Call 108 Emergency immediately.",
        "Place hands in center of chest.",
        "Push hard and fast (100-120 compressions per min).",
        "Allow chest to recoil completely between compressions."
      ]
    },
    {
      id: "fa-2",
      title: "Choking (Heimlich Maneuver)",
      category: "Critical",
      icon: "wind",
      steps: [
        "Stand behind the victim and wrap arms around waist.",
        "Make a fist with one hand above navel.",
        "Grasp fist with other hand and give quick upward thrusts.",
        "Repeat until object is dislodged."
      ]
    },
    {
      id: "fa-3",
      title: "Severe Bleeding Control",
      category: "Trauma",
      icon: "droplet",
      steps: [
        "Apply direct pressure to wound using sterile cloth.",
        "Elevate injured limb above heart level.",
        "Apply pressure bandage firmly.",
        "Do not remove blood-soaked bandages; layer new ones on top."
      ]
    },
    {
      id: "fa-4",
      title: "Thermal Burn First Response",
      category: "Burns",
      icon: "flame",
      steps: [
        "Cool burn immediately under cool running tap water for 10-20 mins.",
        "Do not apply ice, butter, or ointments.",
        "Cover burn loosely with clean cling wrap or non-stick dressing.",
        "Seek medical care if burn is larger than victim's palm."
      ]
    }
  ],

  // Blood Compatibility Matrix & Active Requests
  bloodCompatibility: [
    { type: "O-", canGiveTo: "Universal Donor (All Blood Types)", canReceiveFrom: "O-" },
    { type: "O+", canGiveTo: "O+, A+, B+, AB+", canReceiveFrom: "O+, O-" },
    { type: "A-", canGiveTo: "A-, A+, AB-, AB+", canReceiveFrom: "A-, O-" },
    { type: "A+", canGiveTo: "A+, AB+", canReceiveFrom: "A+, A-, O+, O-" },
    { type: "B-", canGiveTo: "B-, B+, AB-, AB+", canReceiveFrom: "B-, O-" },
    { type: "B+", canGiveTo: "B+, AB+", canReceiveFrom: "B+, B-, O+, O-" },
    { type: "AB-", canGiveTo: "AB-, AB+", canReceiveFrom: "AB-, A-, B-, O-" },
    { type: "AB+", canGiveTo: "AB+ Only", canReceiveFrom: "Universal Recipient (All Types)" }
  ],

  bloodRequests: [
    { id: "req-1", patientName: "Marcus Vance", bloodGroup: "O-", units: 2, hospital: "CuraCare Metro Hospital", urgency: "URGENT", status: "Active Search" },
    { id: "req-2", patientName: "Anita Roy", bloodGroup: "A+", units: 1, hospital: "CityCare Polyclinic", urgency: "Normal", status: "Units Fulfilled" }
  ],

  // Store Offers & Coupons
  storeOffers: [
    { code: "CURA20", title: "20% OFF First Order", subtitle: "On orders above $30", discount: "20% OFF", bg: "from-teal-600 to-cyan-700" },
    { code: "GENERIC50", title: "Flat $15 Cashback", subtitle: "When buying Generic Alternatives", discount: "$15 OFF", bg: "from-indigo-600 to-purple-700" },
    { code: "FREESHIP", title: "Free Express Shipping", subtitle: "Same-day doorstep delivery", discount: "FREE SHIP", bg: "from-emerald-600 to-teal-700" }
  ],

  // Facilities dataset matching Maps reference UI
  mapFacilities: [
    {
      id: "fac-1",
      name: "MedPlus Pharmacy",
      type: "Nearby Pharmacies",
      lat: 37.7780,
      lng: -122.4150,
      address: "120 Market Street, Bay Area",
      phone: "+1 (800) 555-0211",
      distanceKm: 0.4,
      etaMins: 2,
      rating: 4.9,
      is24x7: true,
      openHours: "Open 24 hours",
      icon: "plus",
      colorClass: "teal",
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-2",
      name: "City Care Hospital",
      type: "Hospitals",
      lat: 37.7749,
      lng: -122.4194,
      address: "500 Healthcare Blvd, Suite 100",
      phone: "+1 (800) 555-0199",
      distanceKm: 0.8,
      etaMins: 4,
      rating: 4.9,
      is24x7: true,
      openHours: "Open 24 hours",
      bedsAvailable: 14,
      icuBeds: 5,
      erWaitTimeMins: 12,
      icon: "building-2",
      colorClass: "indigo",
      image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-3",
      name: "Health First Labs",
      type: "Labs",
      lat: 37.7795,
      lng: -122.4280,
      address: "420 Science Drive, Medical District",
      phone: "+1 (800) 555-0455",
      distanceKm: 1.2,
      etaMins: 7,
      rating: 4.8,
      is24x7: false,
      openHours: "Open 7:00 AM – 9:00 PM",
      icon: "flask-conical",
      colorClass: "purple",
      image: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-4",
      name: "LifeLine Clinic",
      type: "Clinics",
      lat: 37.7710,
      lng: -122.4230,
      address: "888 Mission Ave, Downtown",
      phone: "+1 (800) 555-0344",
      distanceKm: 1.5,
      etaMins: 8,
      rating: 4.7,
      is24x7: false,
      openHours: "Open 9:00 AM – 8:00 PM",
      icon: "stethoscope",
      colorClass: "amber",
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-5",
      name: "Red Cross Regional Blood Bank & Donor Depot",
      type: "Blood Banks",
      lat: 37.7680,
      lng: -122.4280,
      address: "101 Red Cross Way",
      phone: "+1 (800) 555-0911",
      distanceKm: 2.1,
      etaMins: 9,
      rating: 4.9,
      is24x7: true,
      bloodStock: { "O-": 12, "O+": 34, "A+": 28, "B+": 22, "AB-": 4 },
      donorBedsAvailable: 8,
      image: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-6",
      name: "CuraAssist Rapid Response Ambulance Unit #4",
      type: "Ambulance",
      lat: 37.7760,
      lng: -122.4180,
      address: "Stationed at Civic Center Plaza",
      phone: "108 / Direct +1 (800) 555-0000",
      distanceKm: 0.3,
      etaMins: 3,
      rating: 5.0,
      is24x7: true,
      ambulanceType: "Advanced Life Support (ALS) ICU Ambulance",
      oxygenOnBoard: true,
      ventilatorEquipped: true,
      paramedicTeam: "Paramedic Dave Miller & EMT Lisa Ray",
      image: "https://images.unsplash.com/photo-1587745416684-47953f16f02f?auto=format&fit=crop&q=80&w=400"
    }
  ],

  // Customer Reviews & Feedback Dataset
  reviews: [
    { id: "rev-1", name: "David K.", rating: 5, date: "2 days ago", comment: "The Generic Alternative feature saved me over $75 on my monthly cholesterol meds! Delivery was fast.", verified: true },
    { id: "rev-2", name: "Maria Garcia", rating: 5, date: "1 week ago", comment: "The Emergency button gave my elderly mom peace of mind. Live location sharing worked flawlessly.", verified: true },
    { id: "rev-3", name: "James L.", rating: 4, date: "2 weeks ago", comment: "Great prescription scanner! It read my handwritten doctor slip instantly.", verified: true }
  ],


};

// Internationalization (i18n) Translations Dictionary
const I18N = {
  en: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "AI-Powered Smart Healthcare Platform",
    home: "Home",
    store: "Store",
    maps: "Maps",
    profile: "Profile",
    bloodSupport: "Blood Support",
    feedback: "Feedback & Reviews",
    sosButton: "Emergency",
    scanItem: "Scan Item / Prescription",
    aiAssistant: "AI Assistant",
    healthDashboard: "Health Dashboard",
    medicineSchedule: "Medicine Schedule",
    healthRecords: "Health Records",
    emergency: "Emergency",
    progress: "Progress & Adherence",
    searchMedicine: "Search Medicine...",
    genericAlternatives: "Generic Alternatives",
    nearbyPharmacies: "Nearby Pharmacies",
    hospitals: "Hospitals",
    liveAvailability: "Live Availability",
    cart: "Cart",
    checkout: "Checkout",
    orders: "My Orders",
    familySwitch: "Family Profile",
    language: "Language",
    darkTheme: "Dark Mode",
    lightTheme: "Light Mode",
    hippaBadge: "HIPAA Compliant Data Storage"
  },
  es: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "Plataforma de Salud Inteligente con IA",
    home: "Inicio",
    store: "Tienda",
    maps: "Mapas",
    profile: "Perfil",
    bloodSupport: "Soporte de Sangre",
    feedback: "Reseñas y Comentarios",
    sosButton: "Emergencia",
    scanItem: "Escanear Receta / Medicina",
    aiAssistant: "Asistente IA",
    healthDashboard: "Panel de Salud",
    medicineSchedule: "Horario de Medicamentos",
    healthRecords: "Historial Médico",
    emergency: "Emergencia",
    progress: "Progreso y Adherencia",
    searchMedicine: "Buscar Medicamento...",
    genericAlternatives: "Alternativas Genéricas",
    nearbyPharmacies: "Farmacias Cercanas",
    hospitals: "Hospitales",
    liveAvailability: "Disponibilidad en Vivo",
    cart: "Carrito",
    checkout: "Pagar",
    orders: "Mis Pedidos",
    familySwitch: "Perfil Familiar",
    language: "Idioma",
    darkTheme: "Modo Oscuro",
    lightTheme: "Modo Claro",
    hippaBadge: "Almacenamiento Compatible con HIPAA"
  },
  hi: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "एआई-संचालित स्मार्ट स्वास्थ्य सेवा",
    home: "होम",
    store: "मेडिकल स्टोर",
    maps: "नक्शा व अस्पताल",
    profile: "प्रोफ़ाइल",
    bloodSupport: "ब्लड सपोर्ट",
    feedback: "फीडबैक व समीक्षाएँ",
    sosButton: "इमरजेंसी",
    scanItem: "दवा या पर्ची स्कैन करें",
    aiAssistant: "एआई सहायक",
    healthDashboard: "हेल्थ डैशबोर्ड",
    medicineSchedule: "दवाओं का समय",
    healthRecords: "स्वास्थ्य रिकॉर्ड",
    emergency: "इमरजेंसी",
    progress: "स्वास्थ्य प्रगति",
    searchMedicine: "दवा खोजें...",
    genericAlternatives: "जेनेरिक विकल्प",
    nearbyPharmacies: "निकटतम मेडिकल स्टोर",
    hospitals: "अस्पताल",
    liveAvailability: "लाइव बेड उपलब्धता",
    cart: "कार्ट",
    checkout: "ऑर्डर करें",
    orders: "मेरे ऑर्डर",
    familySwitch: "परिवार प्रोफ़ाइल",
    language: "भाषा",
    darkTheme: "डार्क मोड",
    lightTheme: "लाइट मोड",
    hippaBadge: "सुरक्षित डेटा एन्क्रिप्शन"
  },
  fr: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "Plateforme de Santé Intelligente par IA",
    home: "Accueil",
    store: "Boutique",
    maps: "Cartes & Hôpitaux",
    profile: "Profil",
    bloodSupport: "Don de Sang",
    feedback: "Avis et Commentaires",
    sosButton: "Urgence",
    scanItem: "Scanner Ordonnance",
    aiAssistant: "Assistant IA",
    healthDashboard: "Tableau de Bord Santé",
    medicineSchedule: "Rappel Médicaments",
    healthRecords: "Dossier Médical",
    emergency: "Urgence",
    progress: "Progrès Santé",
    searchMedicine: "Rechercher Médicament...",
    genericAlternatives: "Alternatives Génériques",
    nearbyPharmacies: "Pharmacies Proches",
    hospitals: "Hôpitaux",
    liveAvailability: "Disponibilité en Direct",
    cart: "Panier",
    checkout: "Commander",
    orders: "Mes Commandes",
    familySwitch: "Profil Familial",
    language: "Langue",
    darkTheme: "Mode Sombre",
    lightTheme: "Mode Clair",
    hippaBadge: "Conforme aux Normes HIPAA"
  },
  de: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "KI-Gestützte Gesundheitsplattform",
    home: "Startseite",
    store: "Apotheke",
    maps: "Karten & Kliniken",
    profile: "Profil",
    bloodSupport: "Blutspende-Support",
    feedback: "Feedback & Bewertungen",
    sosButton: "Notfall",
    scanItem: "Rezept Scannen",
    aiAssistant: "KI-Assistent",
    healthDashboard: "Gesundheits-Dashboard",
    medicineSchedule: "Medikamentenplan",
    healthRecords: "Gesundheitsakte",
    emergency: "Notfall",
    progress: "Fortschritt & Berichte",
    searchMedicine: "Medikament Suchen...",
    genericAlternatives: "Generika-Alternativen",
    nearbyPharmacies: "Apotheken in der Nähe",
    hospitals: "Krankenhäuser",
    liveAvailability: "Live-Verfügbarkeit",
    cart: "Warenkorb",
    checkout: "Kasse",
    orders: "Meine Bestellungen",
    familySwitch: "Familienprofil",
    language: "Sprache",
    darkTheme: "Dunkelmodus",
    lightTheme: "Hellmodus",
    hippaBadge: "DSGVO & HIPAA Konform"
  }
};
