// CuraAssist CareHub - Data Store & Internationalization Dictionaries

const INITIAL_DATA = {
  // Auth State Mock
  userAuth: {
    isLoggedIn: false,
    user: {
      name: "Guest User",
      email: "",
      phone: "",
      token: ""
    }
  },

  // Active User & Family Members
  familyMembers: [
    {
      id: "mem-1",
      name: "Registered User",
      relation: "Self (Primary)",
      age: 30,
      gender: "User",
      bloodGroup: "O+",
      height: "175 cm",
      weight: "70 kg",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250",
      allergies: ["None"],
      conditions: ["General Wellness"],
      surgeries: ["None"],
      vitals: {
        heartRate: 72,
        bp: "120/80",
        spO2: 98,
        glucose: 95,
        sleepHours: 7.5,
        steps: 8420,
        stepGoal: 10000
      }
    }
  ],

  // Medicine Schedule per member
  medicineSchedule: {},

  // Health Records
  healthRecords: [],

  // Detailed Medicines List with Barcode, Usage, Side Effects & Warnings
  medicines: [
    {
      id: "med-proto-1",
      name: "NeuroBoost Focus 250mg (Prototype Showcase)",
      genericName: "Nootropic Brain & Memory Complex",
      brandName: "NeuroBoost Focus",
      barcode: "8909990001111",
      category: "Prototype Specials",
      subcategory: "Nootropic Focus",
      price: 48.00,
      genericPrice: 18.00,
      savingsPercent: 62,
      rating: 5.0,
      reviewsCount: 240,
      rxRequired: false,
      form: "Capsule",
      packSize: "30 Capsules",
      dosage: "1 Capsule in morning with breakfast",
      salt: "Bacopa Monnieri 150mg + L-Theanine 100mg",
      manufacturer: "CuraAssist BioLabs",
      genericManufacturer: "NeuroCare Generics",
      description: "⭐ [PROTOTYPE SHOWCASE MEDICINE] High-potency cognitive health formula for focus, mental clarity, and memory retention.",
      sideEffects: ["None under recommended dosage"],
      usageInstructions: "Take 1 capsule morning after food.",
      safetyWarnings: "Do not exceed recommended dose.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-proto-2",
      name: "CuraCardio Protect 10mg (Prototype Smart Pill)",
      genericName: "CoQ10 + Omega-3 Heart & BP Support",
      brandName: "CuraCardio Protect",
      barcode: "8909990002222",
      category: "Prototype Specials",
      subcategory: "Cardiovascular Support",
      price: 65.00,
      genericPrice: 24.00,
      savingsPercent: 63,
      rating: 4.9,
      reviewsCount: 310,
      rxRequired: false,
      form: "Softgel Capsule",
      packSize: "30 Softgels",
      dosage: "1 Softgel daily after dinner",
      salt: "Coenzyme Q10 100mg + Omega-3 300mg",
      manufacturer: "CuraAssist CardioCare",
      genericManufacturer: "Cardio Generics",
      description: "⭐ [PROTOTYPE SHOWCASE MEDICINE] Advanced heart and blood pressure formula with CoQ10 & Omega-3.",
      sideEffects: ["Mild indigestion if taken empty stomach"],
      usageInstructions: "Swallow after dinner with water.",
      safetyWarnings: "Consult physician if taking blood thinners.",
      image: "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-proto-3",
      name: "ImmuneShield Max 24hr Emergency Defense",
      genericName: "Zinc + Vitamin C + D3 + Elderberry Extract",
      brandName: "ImmuneShield Max",
      barcode: "8909990003333",
      category: "Prototype Specials",
      subcategory: "Effervescent Drink",
      price: 29.00,
      genericPrice: 10.00,
      savingsPercent: 65,
      rating: 5.0,
      reviewsCount: 180,
      rxRequired: false,
      form: "Effervescent Tablet",
      packSize: "20 Tablets",
      dosage: "Dissolve 1 tablet in 200ml water daily",
      salt: "Zinc 20mg + Vit C 1000mg + Vit D3 4000IU",
      manufacturer: "CuraAssist Immunity Labs",
      genericManufacturer: "Immuno Health",
      description: "⭐ [PROTOTYPE SHOWCASE MEDICINE] Fast-dissolving effervescent immunity booster drink for seasonal defense.",
      sideEffects: ["None"],
      usageInstructions: "Drop 1 tablet into water, let fizz completely and drink.",
      safetyWarnings: "Store in airtight cap.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-example-temp",
      name: "CuraAssist Example Health Boost 500mg (Temporary Sample)",
      genericName: "Multivitamin & Mineral Complex + Zinc",
      brandName: "CuraBoost Example",
      barcode: "8901234567890",
      category: "Vitamins & Supplements",
      subcategory: "Immunity Booster",
      price: 35.00,
      genericPrice: 12.00,
      savingsPercent: 65,
      rating: 5.0,
      reviewsCount: 120,
      rxRequired: false,
      form: "Capsule",
      packSize: "30 Capsules",
      dosage: "1 Capsule daily post breakfast",
      salt: "Zinc 15mg + Vit C 500mg + Vit D3 2000IU",
      manufacturer: "CuraAssist Health Labs",
      genericManufacturer: "HealthCare Generics",
      description: "⭐ [EXAMPLE TEMPORARY MEDICINE] High-potency daily wellness supplement with Zinc, Vitamin C, and D3 for immune defense and energy. Added temporarily for feature demonstration & store testing.",
      sideEffects: ["None under normal dosage"],
      usageInstructions: "Swallow 1 capsule daily after breakfast with water.",
      safetyWarnings: "Keep out of reach of children. Store in a cool dry place.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-para",
      name: "Paracetamol 650 mg",
      genericName: "Paracetamol / Acetaminophen",
      brandName: "Paracetamol 650",
      barcode: "8907771112233",
      category: "Pain Relief",
      subcategory: "Fever Reducer",
      price: 28.00,
      genericPrice: 8.00,
      savingsPercent: 71,
      rating: 4.9,
      reviewsCount: 890,
      rxRequired: false,
      form: "Tablet",
      packSize: "15 Tablets",
      dosage: "1 Tablet every 6 hours as needed for fever/pain",
      salt: "Paracetamol 650mg",
      manufacturer: "Micro Labs",
      genericManufacturer: "Cipla Generics",
      description: "Effective relief from fever, mild to moderate headache, body pain, and inflammation.",
      sideEffects: ["Mild nausea"],
      usageInstructions: "Take with or without food. Do not exceed 4000mg in 24 hours.",
      safetyWarnings: "Overdose can cause serious liver injury.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-vitc",
      name: "Vitamin C 500 mg",
      genericName: "Ascorbic Acid",
      brandName: "Celin 500",
      barcode: "8908882223344",
      category: "Vitamins & Supplements",
      subcategory: "Immunity Booster",
      price: 45.00,
      genericPrice: 15.00,
      savingsPercent: 66,
      rating: 4.8,
      reviewsCount: 450,
      rxRequired: false,
      form: "Tablet",
      packSize: "30 Tablets",
      dosage: "1 Tablet daily after breakfast",
      salt: "Ascorbic Acid 500mg",
      manufacturer: "GSK Health",
      genericManufacturer: "Sun Pharma",
      description: "Essential antioxidant vitamin for boosting collagen synthesis and immune defense.",
      sideEffects: ["Mild stomach acidity if taken on empty stomach"],
      usageInstructions: "Chew or swallow tablet with water after meal.",
      safetyWarnings: "Consult doctor if history of kidney stones.",
      image: "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-aug",
      name: "Augmentin 625 Duo Tablet",
      genericName: "Amoxicillin & Clavulanate Potassium 625mg",
      brandName: "Augmentin 625",
      barcode: "8902221113344",
      category: "Antibiotics",
      subcategory: "Broad Spectrum Antibiotic",
      price: 215.00,
      genericPrice: 85.00,
      savingsPercent: 60,
      rating: 4.8,
      reviewsCount: 320,
      rxRequired: true,
      form: "Tablet",
      packSize: "10 Tablets",
      dosage: "1 Tablet twice daily post meals for 5-7 days",
      salt: "Amoxicillin 500mg + Clavulanic Acid 125mg",
      manufacturer: "GSK India",
      genericManufacturer: "Mankind Pharma",
      description: "Effective treatment for bacterial chest infections, sinusitis, ENT, and soft tissue infections.",
      sideEffects: ["Diarrhea", "Nausea"],
      usageInstructions: "Take at start of a meal for best absorption.",
      safetyWarnings: "Do not take if allergic to penicillin.",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-pan40",
      name: "Pan 40 Tablet",
      genericName: "Pantoprazole Sodium 40mg",
      brandName: "Pan 40",
      barcode: "8903332224455",
      category: "Gastroenterology",
      subcategory: "Antacid / PPI",
      price: 145.00,
      genericPrice: 40.00,
      savingsPercent: 72,
      rating: 4.9,
      reviewsCount: 610,
      rxRequired: false,
      form: "Tablet",
      packSize: "15 Tablets",
      dosage: "1 Tablet in morning 30 minutes before breakfast",
      salt: "Pantoprazole 40mg",
      manufacturer: "Alkem Labs",
      genericManufacturer: "Cipla Generics",
      description: "Provides 24-hour relief from acid reflux, GERD, heartburn, and stomach ulcers.",
      sideEffects: ["Mild headache"],
      usageInstructions: "Swallow whole with water before breakfast.",
      safetyWarnings: "Do not crush or chew tablet.",
      image: "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-azee",
      name: "Azee 500 Tablet",
      genericName: "Azithromycin 500mg",
      brandName: "Azee 500",
      barcode: "8904443335566",
      category: "Antibiotics",
      subcategory: "Macrolide Antibiotic",
      price: 120.00,
      genericPrice: 45.00,
      savingsPercent: 62,
      rating: 4.7,
      reviewsCount: 410,
      rxRequired: true,
      form: "Tablet",
      packSize: "5 Tablets",
      dosage: "1 Tablet once daily for 3-5 days",
      salt: "Azithromycin 500mg",
      manufacturer: "Cipla Ltd",
      genericManufacturer: "Sun Pharma",
      description: "Effective single-dose daily antibiotic for typhoid, respiratory, and throat infections.",
      sideEffects: ["Stomach cramps", "Mild diarrhea"],
      usageInstructions: "Take 1 hour before or 2 hours after food.",
      safetyWarnings: "Avoid taking antacids at the same time.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-glyco",
      name: "Glycomet SR 500 Tablet",
      genericName: "Metformin 500mg Sustained Release",
      brandName: "Glycomet SR",
      barcode: "8905554446677",
      category: "Diabetes Care",
      subcategory: "Oral Hypoglycemic",
      price: 42.00,
      genericPrice: 15.00,
      savingsPercent: 64,
      rating: 4.9,
      reviewsCount: 950,
      rxRequired: true,
      form: "Tablet",
      packSize: "15 Tablets",
      dosage: "1 Tablet twice daily after meals",
      salt: "Metformin 500mg SR",
      manufacturer: "USV Ltd",
      genericManufacturer: "Zydus Healthcare",
      description: "Gold-standard medication for controlling high blood sugar levels in Type 2 Diabetes.",
      sideEffects: ["Nausea", "Loose stools initially"],
      usageInstructions: "Take with food to minimize stomach upset.",
      safetyWarnings: "Regular blood sugar monitoring recommended.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-montair",
      name: "Montair LC Tablet",
      genericName: "Montelukast 10mg + Levocetirizine 5mg",
      brandName: "Montair LC",
      barcode: "8906665557788",
      category: "Allergy & Asthma",
      subcategory: "Anti-allergic",
      price: 185.00,
      genericPrice: 60.00,
      savingsPercent: 67,
      rating: 4.8,
      reviewsCount: 380,
      rxRequired: true,
      form: "Tablet",
      packSize: "10 Tablets",
      dosage: "1 Tablet at night before sleep",
      salt: "Montelukast 10mg + Levocetirizine 5mg",
      manufacturer: "Cipla Ltd",
      genericManufacturer: "Lupin Ltd",
      description: "Dual-action combination for allergic rhinitis, sneezing, watery eyes, and asthma symptoms.",
      sideEffects: ["Mild drowsiness"],
      usageInstructions: "Take once daily in evening or night.",
      safetyWarnings: "May cause mild sedation.",
      image: "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-storvas",
      name: "Storvas 20 Tablet",
      genericName: "Atorvastatin 20mg",
      brandName: "Storvas 20",
      barcode: "8907776668899",
      category: "Cardiology",
      subcategory: "Statin / Lipid Lowering",
      price: 210.00,
      genericPrice: 70.00,
      savingsPercent: 66,
      rating: 4.8,
      reviewsCount: 520,
      rxRequired: true,
      form: "Tablet",
      packSize: "15 Tablets",
      dosage: "1 Tablet at bedtime",
      salt: "Atorvastatin 20mg",
      manufacturer: "Sun Pharma",
      genericManufacturer: "Torrent Pharma",
      description: "Lowers bad cholesterol (LDL) and triglycerides, significantly reducing heart attack risks.",
      sideEffects: ["Mild muscle pain"],
      usageInstructions: "Take daily at evening bedtime.",
      safetyWarnings: "Report severe muscle pain to doctor.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-combiflam",
      name: "Combiflam Tablet",
      genericName: "Ibuprofen 400mg + Paracetamol 325mg",
      brandName: "Combiflam",
      barcode: "8901112223344",
      category: "Pain Relief",
      subcategory: "Analgesic & Anti-inflammatory",
      price: 45.00,
      genericPrice: 15.00,
      savingsPercent: 66,
      rating: 4.9,
      reviewsCount: 1100,
      rxRequired: false,
      form: "Tablet",
      packSize: "20 Tablets",
      dosage: "1 Tablet twice daily post meals",
      salt: "Ibuprofen 400mg + Paracetamol 325mg",
      manufacturer: "Sanofi India",
      genericManufacturer: "Micro Labs",
      description: "Dual relief for muscle pains, toothaches, headache, joint pain, and menstrual cramps.",
      sideEffects: ["Mild heartburn"],
      usageInstructions: "Always take after food.",
      safetyWarnings: "Do not take on empty stomach.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-dolo",
      name: "Dolo 650 mg",
      genericName: "Paracetamol Extended Relief",
      brandName: "Dolo (Micro Labs)",
      barcode: "8909993334455",
      category: "Pain Relief",
      subcategory: "Fever Reducer",
      price: 30.00,
      genericPrice: 10.00,
      savingsPercent: 67,
      rating: 4.9,
      reviewsCount: 1250,
      rxRequired: false,
      form: "Tablet",
      packSize: "15 Tablets",
      dosage: "1 Tablet every 6 hours",
      salt: "Paracetamol 650mg",
      manufacturer: "Micro Labs Ltd",
      genericManufacturer: "Generic Care",
      description: "Fast relief from fever, flu symptoms, joint pain, and muscle ache.",
      sideEffects: ["Rare allergic skin rash"],
      usageInstructions: "Swallow whole with water.",
      safetyWarnings: "Avoid alcohol intake while taking paracetamol.",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-1",
      name: "Lipitor",
      genericName: "Atorvastatin Calcium",
      brandName: "Lipitor (Pfizer)",
      barcode: "8901234567890",
      category: "Prescription",
      subcategory: "Heart & Cholesterol",
      price: 48.50,
      genericPrice: 9.20,
      savingsPercent: 81,
      rating: 4.8,
      reviewsCount: 342,
      rxRequired: true,
      form: "Tablet",
      packSize: "30 Tablets (20mg)",
      dosage: "20mg once daily in the evening",
      salt: "Atorvastatin 20mg",
      manufacturer: "Pfizer Pharmaceuticals",
      genericManufacturer: "Teva / Cipla Generics",
      description: "Lowers LDL cholesterol and triglycerides in blood while raising HDL. Reduces risk of heart attack and stroke.",
      sideEffects: ["Mild muscle pain", "Headache", "Nausea", "Elevated liver enzymes"],
      usageInstructions: "Swallow tablet whole with a glass of water. Avoid grapefruit juice while taking this medication.",
      safetyWarnings: "Do not use during pregnancy. Inform doctor if severe muscle weakness occurs.",
      image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-2",
      name: "Glucophage",
      genericName: "Metformin Hydrochloride XR",
      brandName: "Glucophage (Merck)",
      barcode: "8909876543210",
      category: "Diabetes Care",
      subcategory: "Blood Glucose Control",
      price: 36.00,
      genericPrice: 7.50,
      savingsPercent: 79,
      rating: 4.7,
      reviewsCount: 215,
      rxRequired: true,
      form: "Extended Release Tablet",
      packSize: "60 Tablets (500mg)",
      dosage: "500mg twice daily with meals",
      salt: "Metformin HCl 500mg",
      manufacturer: "Merck Healthcare",
      genericManufacturer: "Sun Pharma Generics",
      description: "First-line medication for treatment of type 2 diabetes, improves insulin sensitivity and lowers liver glucose production.",
      sideEffects: ["Upset stomach", "Diarrhea", "Metallic taste", "Vitamin B12 depletion"],
      usageInstructions: "Take with meals to reduce gastrointestinal side effects.",
      safetyWarnings: "Not recommended for patients with severe kidney impairment.",
      image: "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-3",
      name: "Ventolin HFA",
      genericName: "Albuterol Sulfate Inhaler",
      brandName: "Ventolin (GSK)",
      barcode: "8905554443322",
      category: "Respiratory",
      subcategory: "Asthma & COPD",
      price: 64.00,
      genericPrice: 18.00,
      savingsPercent: 72,
      rating: 4.9,
      reviewsCount: 480,
      rxRequired: true,
      form: "Inhaler",
      packSize: "200 Actuations (90mcg)",
      dosage: "1-2 puffs every 4-6 hours as needed for bronchospasm",
      salt: "Albuterol 90mcg",
      manufacturer: "GlaxoSmithKline",
      genericManufacturer: "Prasco / Perrigo",
      description: "Fast-acting bronchodilator for relieving shortness of breath and wheezing in asthma attacks.",
      sideEffects: ["Shakiness", "Increased heart rate", "Nervousness", "Throat irritation"],
      usageInstructions: "Shake well before use. Inhale deeply while depressing canister.",
      safetyWarnings: "Seek immediate medical care if shortness of breath persists after 2 puffs.",
      image: "https://images.unsplash.com/photo-1550572017-edd951b55104?auto=format&fit=crop&q=80&w=300"
    },
    {
      id: "med-4",
      name: "Centrum Adult Multivitamin",
      genericName: "Daily Multi-Mineral & Vitamin Complex",
      brandName: "Centrum Complete",
      barcode: "8901112223334",
      category: "Vitamins & Supplements",
      subcategory: "Wellness",
      price: 19.99,
      genericPrice: 11.50,
      savingsPercent: 42,
      rating: 4.6,
      reviewsCount: 620,
      rxRequired: false,
      form: "Gummy / Tablet",
      packSize: "100 Gummies",
      dosage: "1 Gummy daily with food",
      salt: "Vitamins A, C, D3, E, B6, B12, Zinc, Iron",
      manufacturer: "Haleon",
      genericManufacturer: "Nature Made / CarePlus",
      description: "Complete daily nutrition support for immunity, energy metabolism, and cellular vitality.",
      sideEffects: ["Mild constipation if taken on empty stomach"],
      usageInstructions: "Chew thoroughly before swallowing.",
      safetyWarnings: "Keep out of reach of children. Accidental overdose of iron-containing products is a leading cause of fatal poisoning in children.",
      image: "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&q=80&w=300"
    }
  ],

  // First Aid Guide Dataset
  firstAidGuides: [
    {
      id: "fa-1",
      title: "Cardiopulmonary Resuscitation (CPR)",
      category: "Critical",
      icon: "heart-pulse",
      steps: [
        "Call 108 Emergency immediately.",
        "Place hands in center of chest.",
        "Push hard and fast (100-120 compressions per min).",
        "Allow chest to recoil completely between compressions."
      ]
    },
    {
      id: "fa-2",
      title: "Choking (Heimlich Maneuver)",
      category: "Critical",
      icon: "wind",
      steps: [
        "Stand behind the victim and wrap arms around waist.",
        "Make a fist with one hand above navel.",
        "Grasp fist with other hand and give quick upward thrusts.",
        "Repeat until object is dislodged."
      ]
    },
    {
      id: "fa-3",
      title: "Severe Bleeding Control",
      category: "Trauma",
      icon: "droplet",
      steps: [
        "Apply direct pressure to wound using sterile cloth.",
        "Elevate injured limb above heart level.",
        "Apply pressure bandage firmly.",
        "Do not remove blood-soaked bandages; layer new ones on top."
      ]
    },
    {
      id: "fa-4",
      title: "Thermal Burn First Response",
      category: "Burns",
      icon: "flame",
      steps: [
        "Cool burn immediately under cool running tap water for 10-20 mins.",
        "Do not apply ice, butter, or ointments.",
        "Cover burn loosely with clean cling wrap or non-stick dressing.",
        "Seek medical care if burn is larger than victim's palm."
      ]
    }
  ],

  // Blood Compatibility Matrix & Active Requests
  bloodCompatibility: [
    { type: "O-", canGiveTo: "Universal Donor (All Blood Types)", canReceiveFrom: "O-" },
    { type: "O+", canGiveTo: "O+, A+, B+, AB+", canReceiveFrom: "O+, O-" },
    { type: "A-", canGiveTo: "A-, A+, AB-, AB+", canReceiveFrom: "A-, O-" },
    { type: "A+", canGiveTo: "A+, AB+", canReceiveFrom: "A+, A-, O+, O-" },
    { type: "B-", canGiveTo: "B-, B+, AB-, AB+", canReceiveFrom: "B-, O-" },
    { type: "B+", canGiveTo: "B+, AB+", canReceiveFrom: "B+, B-, O+, O-" },
    { type: "AB-", canGiveTo: "AB-, AB+", canReceiveFrom: "AB-, A-, B-, O-" },
    { type: "AB+", canGiveTo: "AB+ Only", canReceiveFrom: "Universal Recipient (All Types)" }
  ],

  bloodRequests: [
    { id: "req-1", patientName: "Marcus Vance", bloodGroup: "O-", units: 2, hospital: "CuraCare Metro Hospital", urgency: "URGENT", status: "Active Search" },
    { id: "req-2", patientName: "Anita Roy", bloodGroup: "A+", units: 1, hospital: "CityCare Polyclinic", urgency: "Normal", status: "Units Fulfilled" }
  ],

  // Store Offers & Coupons
  storeOffers: [
    { code: "CURA20", title: "20% OFF First Order", subtitle: "On orders above ₹200", discount: "20% OFF", bg: "from-teal-600 to-cyan-700" },
    { code: "GENERIC50", title: "Flat ₹100 Cashback", subtitle: "When buying Generic Alternatives", discount: "₹100 OFF", bg: "from-indigo-600 to-purple-700" },
    { code: "FREESHIP", title: "Free Express Shipping", subtitle: "Same-day doorstep delivery", discount: "FREE SHIP", bg: "from-emerald-600 to-teal-700" }
  ],

  // Facilities dataset matching Maps reference UI
  mapFacilities: [
    {
      id: "fac-1",
      icon: "plus",
      colorClass: "teal",
      image: "https://images.unsplash.com/photo-1576602976047-174e57a47881?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-2",
      name: "City Care Hospital",
      type: "Hospitals",
      lat: 37.7749,
      lng: -122.4194,
      address: "500 Healthcare Blvd, Suite 100",
      phone: "+1 (800) 555-0199",
      distanceKm: 0.8,
      etaMins: 4,
      rating: 4.9,
      is24x7: true,
      openHours: "Open 24 hours",
      bedsAvailable: 14,
      icuBeds: 5,
      erWaitTimeMins: 12,
      icon: "building-2",
      colorClass: "indigo",
      image: "https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-3",
      name: "Health First Labs",
      type: "Labs",
      lat: 37.7795,
      lng: -122.4280,
      address: "420 Science Drive, Medical District",
      phone: "+1 (800) 555-0455",
      distanceKm: 1.2,
      etaMins: 7,
      rating: 4.8,
      is24x7: false,
      openHours: "Open 7:00 AM – 9:00 PM",
      icon: "flask-conical",
      colorClass: "purple",
      image: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-4",
      name: "LifeLine Clinic",
      type: "Clinics",
      lat: 37.7710,
      lng: -122.4230,
      address: "888 Mission Ave, Downtown",
      phone: "+1 (800) 555-0344",
      distanceKm: 1.5,
      etaMins: 8,
      rating: 4.7,
      is24x7: false,
      openHours: "Open 9:00 AM – 8:00 PM",
      icon: "stethoscope",
      colorClass: "amber",
      image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-5",
      name: "Red Cross Regional Blood Bank & Donor Depot",
      type: "Blood Banks",
      lat: 37.7680,
      lng: -122.4280,
      address: "101 Red Cross Way",
      phone: "+1 (800) 555-0911",
      distanceKm: 2.1,
      etaMins: 9,
      rating: 4.9,
      is24x7: true,
      bloodStock: { "O-": 12, "O+": 34, "A+": 28, "B+": 22, "AB-": 4 },
      donorBedsAvailable: 8,
      image: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "fac-6",
      name: "Metro Emergency Trauma Center & Multi-Specialty Hospital",
      type: "Hospitals",
      lat: 37.7760,
      lng: -122.4180,
      address: "Civic Center Medical Plaza",
      phone: "+1 (800) 555-1088",
      distanceKm: 0.3,
      etaMins: 3,
      rating: 5.0,
      is24x7: true,
      openHours: "Open 24 hours",
      icon: "building-2",
      colorClass: "indigo",
      image: "https://images.unsplash.com/photo-1587745416684-47953f16f02f?auto=format&fit=crop&q=80&w=400"
    }
  ],

  // Customer Reviews & Feedback Dataset
  reviews: [
    { id: "rev-1", name: "David K.", rating: 5, date: "2 days ago", comment: "The Generic Alternative feature saved me over $75 on my monthly cholesterol meds! Delivery was fast.", verified: true },
    { id: "rev-2", name: "Maria Garcia", rating: 5, date: "1 week ago", comment: "The Emergency button gave my elderly mom peace of mind. Live location sharing worked flawlessly.", verified: true },
    { id: "rev-3", name: "James L.", rating: 4, date: "2 weeks ago", comment: "Great prescription scanner! It read my handwritten doctor slip instantly.", verified: true }
  ],


};

// Internationalization (i18n) Translations Dictionary
const I18N = {
  en: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "AI-Powered Smart Healthcare Platform",
    home: "Home",
    store: "Store",
    maps: "Maps",
    profile: "Profile",
    bloodSupport: "Blood Support",
    feedback: "Feedback & Reviews",
    sosButton: "Emergency",
    scanItem: "Scan Item / Prescription",
    aiAssistant: "AI Assistant",
    healthDashboard: "Health Dashboard",
    medicineSchedule: "Medicine Schedule",
    healthRecords: "Health Records",
    emergency: "Emergency",
    progress: "Progress & Adherence",
    searchMedicine: "Search Medicine...",
    genericAlternatives: "Generic Alternatives",
    nearbyPharmacies: "Nearby Pharmacies",
    hospitals: "Hospitals",
    liveAvailability: "Live Availability",
    cart: "Cart",
    checkout: "Checkout",
    orders: "My Orders",
    familySwitch: "Family Profile",
    language: "Language",
    darkTheme: "Dark Mode",
    lightTheme: "Light Mode",
    hippaBadge: "HIPAA Compliant Data Storage"
  },
  es: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "Plataforma de Salud Inteligente con IA",
    home: "Inicio",
    store: "Tienda",
    maps: "Mapas",
    profile: "Perfil",
    bloodSupport: "Soporte de Sangre",
    feedback: "Reseñas y Comentarios",
    sosButton: "Emergencia",
    scanItem: "Escanear Receta / Medicina",
    aiAssistant: "Asistente IA",
    healthDashboard: "Panel de Salud",
    medicineSchedule: "Horario de Medicamentos",
    healthRecords: "Historial Médico",
    emergency: "Emergencia",
    progress: "Progreso y Adherencia",
    searchMedicine: "Buscar Medicamento...",
    genericAlternatives: "Alternativas Genéricas",
    nearbyPharmacies: "Farmacias Cercanas",
    hospitals: "Hospitales",
    liveAvailability: "Disponibilidad en Vivo",
    cart: "Carrito",
    checkout: "Pagar",
    orders: "Mis Pedidos",
    familySwitch: "Perfil Familiar",
    language: "Idioma",
    darkTheme: "Modo Oscuro",
    lightTheme: "Modo Claro",
    hippaBadge: "Almacenamiento Compatible con HIPAA"
  },
  hi: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "एआई-संचालित स्मार्ट स्वास्थ्य सेवा",
    home: "होम",
    store: "मेडिकल स्टोर",
    maps: "नक्शा व अस्पताल",
    profile: "प्रोफ़ाइल",
    bloodSupport: "ब्लड सपोर्ट",
    feedback: "फीडबैक व समीक्षाएँ",
    sosButton: "इमरजेंसी",
    scanItem: "दवा या पर्ची स्कैन करें",
    aiAssistant: "एआई सहायक",
    healthDashboard: "हेल्थ डैशबोर्ड",
    medicineSchedule: "दवाओं का समय",
    healthRecords: "स्वास्थ्य रिकॉर्ड",
    emergency: "इमरजेंसी",
    progress: "स्वास्थ्य प्रगति",
    searchMedicine: "दवा खोजें...",
    genericAlternatives: "जेनेरिक विकल्प",
    nearbyPharmacies: "निकटतम मेडिकल स्टोर",
    hospitals: "अस्पताल",
    liveAvailability: "लाइव बेड उपलब्धता",
    cart: "कार्ट",
    checkout: "ऑर्डर करें",
    orders: "मेरे ऑर्डर",
    familySwitch: "परिवार प्रोफ़ाइल",
    language: "भाषा",
    darkTheme: "डार्क मोड",
    lightTheme: "लाइट मोड",
    hippaBadge: "सुरक्षित डेटा एन्क्रिप्शन"
  },
  fr: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "Plateforme de Santé Intelligente par IA",
    home: "Accueil",
    store: "Boutique",
    maps: "Cartes & Hôpitaux",
    profile: "Profil",
    bloodSupport: "Don de Sang",
    feedback: "Avis et Commentaires",
    sosButton: "Urgence",
    scanItem: "Scanner Ordonnance",
    aiAssistant: "Assistant IA",
    healthDashboard: "Tableau de Bord Santé",
    medicineSchedule: "Rappel Médicaments",
    healthRecords: "Dossier Médical",
    emergency: "Urgence",
    progress: "Progrès Santé",
    searchMedicine: "Rechercher Médicament...",
    genericAlternatives: "Alternatives Génériques",
    nearbyPharmacies: "Pharmacies Proches",
    hospitals: "Hôpitaux",
    liveAvailability: "Disponibilité en Direct",
    cart: "Panier",
    checkout: "Commander",
    orders: "Mes Commandes",
    familySwitch: "Profil Familial",
    language: "Langue",
    darkTheme: "Mode Sombre",
    lightTheme: "Mode Clair",
    hippaBadge: "Conforme aux Normes HIPAA"
  },
  de: {
    appTitle: "CuraAssist CareHub",
    appSubtitle: "KI-Gestützte Gesundheitsplattform",
    home: "Startseite",
    store: "Apotheke",
    maps: "Karten & Kliniken",
    profile: "Profil",
    bloodSupport: "Blutspende-Support",
    feedback: "Feedback & Bewertungen",
    sosButton: "Notfall",
    scanItem: "Rezept Scannen",
    aiAssistant: "KI-Assistent",
    healthDashboard: "Gesundheits-Dashboard",
    medicineSchedule: "Medikamentenplan",
    healthRecords: "Gesundheitsakte",
    emergency: "Notfall",
    progress: "Fortschritt & Berichte",
    searchMedicine: "Medikament Suchen...",
    genericAlternatives: "Generika-Alternativen",
    nearbyPharmacies: "Apotheken in der Nähe",
    hospitals: "Krankenhäuser",
    liveAvailability: "Live-Verfügbarkeit",
    cart: "Warenkorb",
    checkout: "Kasse",
    orders: "Meine Bestellungen",
    familySwitch: "Familienprofil",
    language: "Sprache",
    darkTheme: "Dunkelmodus",
    lightTheme: "Hellmodus",
    hippaBadge: "DSGVO & HIPAA Konform"
  }
};
